### ISSUE TITLE
wharton_cosign_auth/remote_user.py", line 15, in configure_user 

### ISSUE THREAD

**Issue by JohnnyP10** [wharton/wharton-cosign-auth#14]
SO i ran into a situation with username uzval where the api returned but email was none so line 15 blows up with user.email = results['email'].replace('exchange.', '') 
AttributeError: 'NoneType' object has no attribute 'replace'

I guess this is good...?  but i would think throwing the error might not be the right way to go.

**Comment by JohnnyP10** [comment]
maybe default to username@wharton without the exchange?

**Comment by JohnnyP10** [comment]
I confirmed that distributed reps can create a wharton account and not enable email so this field can be null so we can't just call replace on it.  not sure if the default value should be username@upenn.edu or username@wharton.upenn.edu.  I was speaking with Jim Denk and he is against defaulting to username@wharton.upenn.edu

**Comment by rollerwhrtn** [comment]
@JohnnyP10 Thanks for the info - I've submitted a pull request that will return None for email if the email field from WISP is null. Django's User auth model should allow None as an acceptable entry for email field: https://docs.djangoproject.com/en/1.10/ref/contrib/auth/#manager-methods
