### ISSUE TITLE
Permissions.py is API always necessary?

### ISSUE THREAD

**Issue by JohnnyP10** [wharton/wharton-cosign-auth#2]
It seems that making an API call for every function might be costly.  We can assume we are dealing with a few main groups and could store those in the user object.  If we are checking for a group that isn't in that main list then use the API to lookup if the user is in the right group.

Just a thought.

**Comment by sturoscy** [comment]
Closing this as per our conversation regarding the django user. We will have to hit the api for now, but I need to add a try/except for empty, null, or errored returns from the api.
