### ISSUE TITLE
Complying with PEP-8

### ISSUE THREAD

**Issue by FlipperPA** [wharton/wharton-cosign-auth#4]
Hey, I'll issue a P.R. for this, but we should make sure to comply with PEP-8, minus the 79 character line limit:

https://www.python.org/dev/peps/pep-0008/

That's the standard across the Python community, and readability counts! :)

**Comment by sturoscy** [comment]
I can take care of it. I'll use the autopep8 plugin you suggested. I'll push right to master since we aren't really changing anything.

**Comment by sturoscy** [comment]
Done.  It is now hopefully PEP8 compliant.  Re-open if you see any other issues.
