### ISSUE TITLE
Bad Authenticaiton Backend?

### ISSUE THREAD

**Issue by JohnnyP10** [wharton/wharton-cosign-auth#8]
Howdy,

The Readme states use the following:
AUTHENTICATION_BACKENDS = (
    'wharton_cosign_auth.remote_user.WhartonRemoteUserBackend',
    'django.contrib.auth.backends.RemoteUserBackend',
)

Doing so seems to prevent local accounts from being able to log into the Admin.  Shouldn't the RemoteUserBackend be ModelBackend?  If you are using WhartonRemoteUserBackend you don't need to also include the standard one do you?

**Comment by sturoscy** [comment]
Good point. You're correct, ModelBackend should replace RemoteUserBackend. I can update the Readme.

**Comment by sturoscy** [comment]
Updated in master and develop. Take a look and I'll close the issue if you're satisfied.

**Comment by JohnnyP10** [comment]
awesome.  I've been banging my head against the computer wondering why my local superuser wasn't working anymore.
